=== kushalsubedi/web-5thsem/xml/alientype.dtd
<?xml version="1.0" encoding="UTF-8" ?>

<!ELEMENT aliens (alien+)>
<!ELEMENT alien (name,age,planet)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ELEMENT planet (#PCDATA)>
<!ATTLIST alien aid ID #REQUIRED>
<!ATTLIST alien lang (python|c) "python">

=== kushalsubedi/web-5thsem/xml/aliens.xml
<?xml version="1.0" encoding="UTF-8" ?>

<!DOCTYPE aliens SYSTEM "alientype.dtd">
<aliens>
    <alien aid ="A1" lang="python">
        <name>Alien 1</name>
        <age>10</age>
        <planet>Earth</planet>
    </alien>
    <alien aid ="A2" lang="c">
        <name>Alien 2</name>
        <age>20</age>
        <planet>Mars</planet>
      
    </alien>
    <alien aid ="A3">
        <name>Alien 3</name>
        <age>30</age>
        <planet>Jupiter</planet>
    </alien>
</aliens>
